// <auto-generated />
using CRUDTASK_CODE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDTASK_CODE.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250405111229_Product")]
    partial class Product
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDTASK_CODE.Models.Product", b =>
                {
                    b.Property<int>("PropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropId"));

                    b.Property<string>("PropName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PropPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PropId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
